// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PattySlaps.Data;

#nullable disable

namespace PattySlapsAPI.Migrations
{
    [DbContext(typeof(PattySlapsDbContext))]
    [Migration("20250312190812_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PattySlaps.Applicant", b =>
                {
                    b.Property<int>("ApplicantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ApplicantID"));

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HourPreferences")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PersonalInfo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ApplicantID");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("PattySlaps.Application", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ApplicationID"));

                    b.Property<int>("ApplicantID")
                        .HasColumnType("int");

                    b.Property<int>("PositionID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ApplicationID");

                    b.HasIndex("ApplicantID");

                    b.HasIndex("PositionID");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("PattySlaps.Branch", b =>
                {
                    b.Property<int>("BranchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BranchID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BranchID");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("PattySlaps.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SIN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Wage")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("BranchID");

                    b.ToTable("Employees");

                    b.HasDiscriminator().HasValue("Employee");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PattySlaps.EndOfShiftReport", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<string>("ChallengesEncountered")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Incident")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MaterialsOutOfStock")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SummaryOfOps")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UnresolvedIssues")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Warning")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ReportID");

                    b.ToTable("EndOfShiftReports");
                });

            modelBuilder.Entity("PattySlaps.HRMS", b =>
                {
                    b.Property<string>("ApplicationsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailTemplatesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JobPostingsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserAccessLevelsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("HRMS");
                });

            modelBuilder.Entity("PattySlaps.HireRequest", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RequestID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RequestingManager")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RequestID");

                    b.ToTable("HireRequests");
                });

            modelBuilder.Entity("PattySlaps.InventoryRecord", b =>
                {
                    b.Property<int>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RecordID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("DiscrepancyFlag")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("EoDQuantity")
                        .HasColumnType("int");

                    b.Property<int>("QuantityUsed")
                        .HasColumnType("int");

                    b.Property<int>("SoDQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RecordID");

                    b.ToTable("InventoryRecords");
                });

            modelBuilder.Entity("PattySlaps.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<string>("CountType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ItemID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("PattySlaps.Kiosk", b =>
                {
                    b.Property<int>("KioskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KioskID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("KioskID");

                    b.ToTable("Kiosks");
                });

            modelBuilder.Entity("PattySlaps.Order", b =>
                {
                    b.Property<int>("Order_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Order_ID"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Order_ID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PattySlaps.OrderItem", b =>
                {
                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("OrderItemID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderID", "ItemID");

                    b.HasIndex("ItemID");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("PattySlaps.Position", b =>
                {
                    b.Property<int>("PositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PositionID"));

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PositionID");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("PattySlaps.ReceptionQCChecklist", b =>
                {
                    b.Property<int>("QCID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("QCID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ItemDefect")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ItemPicture")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("QCID");

                    b.ToTable("ReceptionQCChecklists");
                });

            modelBuilder.Entity("PattySlaps.ShiftSchedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<string>("ConflictAlerts")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SupervisorEmployeeID")
                        .HasColumnType("int");

                    b.HasKey("ScheduleID");

                    b.HasIndex("SupervisorEmployeeID");

                    b.ToTable("ShiftSchedules");
                });

            modelBuilder.Entity("PattySlaps.ShiftScheduleEmployee", b =>
                {
                    b.Property<int>("ScheduleID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("ShiftScheduleEmployeeID")
                        .HasColumnType("int");

                    b.HasKey("ScheduleID", "EmployeeID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("ShiftScheduleEmployee");
                });

            modelBuilder.Entity("PattySlaps.SummaryReport", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<string>("DiscrepancyDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TotalWaste")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ReportID");

                    b.ToTable("SummaryReports");
                });

            modelBuilder.Entity("PattySlaps.WasteRecord", b =>
                {
                    b.Property<int>("WasteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WasteID"));

                    b.Property<int>("InventoryRecordID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("WasteType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("WasteID");

                    b.HasIndex("InventoryRecordID");

                    b.ToTable("WasteRecords");
                });

            modelBuilder.Entity("PattySlaps.HREmployee", b =>
                {
                    b.HasBaseType("PattySlaps.Employee");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("HREmployee");
                });

            modelBuilder.Entity("PattySlaps.Manager", b =>
                {
                    b.HasBaseType("PattySlaps.Employee");

                    b.Property<int>("ManagerID")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Manager");
                });

            modelBuilder.Entity("PattySlaps.Supervisor", b =>
                {
                    b.HasBaseType("PattySlaps.Employee");

                    b.Property<int>("SupervisorID")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Supervisor");
                });

            modelBuilder.Entity("PattySlaps.TeamMember", b =>
                {
                    b.HasBaseType("PattySlaps.Employee");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("TeamMember");
                });

            modelBuilder.Entity("PattySlaps.Application", b =>
                {
                    b.HasOne("PattySlaps.Applicant", null)
                        .WithMany("Applications")
                        .HasForeignKey("ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PattySlaps.Position", null)
                        .WithMany("Applications")
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PattySlaps.Employee", b =>
                {
                    b.HasOne("PattySlaps.Branch", "Branch")
                        .WithMany("Employees")
                        .HasForeignKey("BranchID");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("PattySlaps.OrderItem", b =>
                {
                    b.HasOne("PattySlaps.Item", "Item")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PattySlaps.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PattySlaps.ShiftSchedule", b =>
                {
                    b.HasOne("PattySlaps.Supervisor", null)
                        .WithMany("ShiftSchedules")
                        .HasForeignKey("SupervisorEmployeeID");
                });

            modelBuilder.Entity("PattySlaps.ShiftScheduleEmployee", b =>
                {
                    b.HasOne("PattySlaps.Employee", "Employee")
                        .WithMany("ShiftScheduleEmployees")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PattySlaps.ShiftSchedule", "ShiftSchedule")
                        .WithMany("ShiftScheduleEmployees")
                        .HasForeignKey("ScheduleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ShiftSchedule");
                });

            modelBuilder.Entity("PattySlaps.WasteRecord", b =>
                {
                    b.HasOne("PattySlaps.InventoryRecord", "InventoryRecord")
                        .WithMany("WasteRecords")
                        .HasForeignKey("InventoryRecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryRecord");
                });

            modelBuilder.Entity("PattySlaps.Applicant", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("PattySlaps.Branch", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("PattySlaps.Employee", b =>
                {
                    b.Navigation("ShiftScheduleEmployees");
                });

            modelBuilder.Entity("PattySlaps.InventoryRecord", b =>
                {
                    b.Navigation("WasteRecords");
                });

            modelBuilder.Entity("PattySlaps.Item", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("PattySlaps.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("PattySlaps.Position", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("PattySlaps.ShiftSchedule", b =>
                {
                    b.Navigation("ShiftScheduleEmployees");
                });

            modelBuilder.Entity("PattySlaps.Supervisor", b =>
                {
                    b.Navigation("ShiftSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
